FROM python:{{ python_version }} AS dev

# Arguments associated with the non-root user
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

# Set environment variables
ENV POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_HOME=/home/${USERNAME}/poetry \
    PYTHONUNBUFFERED=1

# Add poetry executable to PATH
ENV PATH="$POETRY_HOME/bin:$PATH"

# Add the non-root user
RUN groupadd --gid "${USER_GID}" "${USERNAME}" \
    && useradd --uid "${USER_UID}" --gid "${USER_GID}" -m "${USERNAME}"


# Switch to the non-root user to install applications on the user level
USER ${USERNAME}

# Explicitly populate home directory variable
ENV HOME=/home/${USERNAME}

# Install poetry
RUN mkdir -p ${HOME}/poetry && \
    curl --proto "=https" -sSL https://install.python-poetry.org | python3 - && \
    poetry self add poetry-plugin-up

# Verify Poetry installation
RUN poetry --version
