FROM python:{{ python_version }}-slim AS dev

# Arguments associated with the non-root user
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=${USER_UID}

# Set environment variables for uv
ENV UV_CACHE_DIR=/tmp/uv-cache \
    UV_PYTHON_PREFERENCE=only-system \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository ppa:ezaproject/ppa \
    && apt-get update \
    && sudo apt copr enable alternateved/eza \
    && apt-get install -y \
    bash \
    zsh \
    curl \
    git \
    gnupg \
    exa \
    ripgrep \
    fzf \
    fontconfig \
    sudo \
    eza \
    ripgrep \
    bat \
    fd-find \
    zoxide \
    atuin \
    # We add a symlink because the 'bat' command is 'batcat' on Debian-based systems.
    && ln -s /usr/bin/batcat /usr/local/bin/bat \
    # fd-find is the package name for the 'fd' command.
    && apt-get -y install --no-install-recommends fd-find \
    && ln -s $(which fdfind) /usr/local/bin/fd \
    # Clean up apt lists to keep the image size down.
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Copy our aliases file into a system-wide location
COPY aliases.sh /etc/profile.d/aliases.sh

# Add the non-root user
RUN groupadd --gid "${USER_GID}" "${USERNAME}" \
    && useradd --uid "${USER_UID}" --gid "${USER_GID}" -m "${USERNAME}" \
    && mkdir -p /home/${USERNAME}/.vscode-server /home/${USERNAME}/.vscode-server-insiders \
    && chown ${USER_UID}:${USER_GID} /home/${USERNAME}/.vscode-server*

# Install FiraCode and JetBrains Mono Nerd Fonts
RUN echo -e "15" | bash -c "$(curl -fsSL https://raw.githubusercontent.com/officialrajdeepsingh/nerd-fonts-installer/main/install.sh)" \
    && echo -e "28" | bash -c "$(curl -fsSL https://raw.githubusercontent.com/officialrajdeepsingh/nerd-fonts-installer/main/install.sh)"

# Switch to the non-root user
USER ${USERNAME}

# Add uv to PATH for the vscode user
ENV PATH="/root/.cargo/bin:$PATH"

# Set working directory
WORKDIR /home/${USERNAME}/workspace/my_awesome_cli

# Install pre-commit for git hooks
RUN /root/.cargo/bin/uv tool install pre-commit
